### PR TITLE
refactor: replace subprocess crate with std::process

### PR DESCRIPTION
**Pull request by Integral-Tech**
Fixes issue #695

### CODE REVIEW

**Comment by Integral-Tech** [comment]
@bee-san I have just fixed the failed workflow in my latest commit, please retrigger it :)

**Comment by bee-san** [comment]
```
error[E0599]: no method named `signal` found for struct `ExitStatus` in the current scope
22
   --> src\scripts\mod.rs:294:46
23
    |
24
294 |                 None if cfg!(unix) => status.signal().unwrap(),
25
    |                                              ^^^^^^ method not found in `ExitStatus`
```

Windows doesn't like this? :(

**Comment by Integral-Tech** [comment]
> ```
> error[E0599]: no method named `signal` found for struct `ExitStatus` in the current scope
> 22
>    --> src\scripts\mod.rs:294:46
> 23
>     |
> 24
> 294 |                 None if cfg!(unix) => status.signal().unwrap(),
> 25
>     |                                              ^^^^^^ method not found in `ExitStatus`
> ```
> 
> Windows doesn't like this? :(

Yes, the [`signal()`](https://doc.rust-lang.org/stable/std/os/unix/process/trait.ExitStatusExt.html#tymethod.signal) method is Unix only

**Comment by Integral-Tech** [comment]
@bee-san Now it should work

**Comment by Integral-Tech** [comment]
@bee-san I just switched to another method of conditional compilation in my latest commit

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
thanks so much!!

**Pull request merged**
