### PR TITLE
Add nixos info

### PR DESCRIPTION
**Pull request by SuperSandro2000**
The package got merged into nixpkgs master earlier. It will be in nixpkgs unstable shortly. I wanted to open this PR already because I am not sure where to link nixos and where to get a image we are allowed to use.

### CODE REVIEW

**Comment by bernardoamc** [comment]
That's awesome @SuperSandro2000, thnak you!  Do you know if it's already on unstable? And we can probably use NixOS logo. Could you add their logo to the   `/pictures` folder?

**Comment by bee-san** [comment]
Just to let you know, I am re-designing the README so we are more of a general scanner than an Nmap specific helper.

I have not pulled this because I am still writing the README :)

**Comment by SuperSandro2000** [comment]
It is already in nixpkgs.unstable. I am not sure from where to get that logo.

@bee-san feel free to include this change. I opened this PR as a reminder to add it to the README.

**Comment by bee-san** [comment]
> It is already in nixpkgs.unstable. I am not sure from where to get that logo.
> 
> @bee-san feel free to include this change. I opened this PR as a reminder to add it to the README.

Absolutely!! Amazing it's in NixOS, I will 100% include this :D

**Comment by SuperSandro2000** [comment]
I've updated the PR with a picture from https://github.com/NixOS/nixos-artwork/tree/master/logo.

**Comment by SuperSandro2000** [comment]
Can this finally be merged? Rebasing this is always a bit difficult and time consuming.

**Comment by bee-san** [comment]
Hey! 

> Just to let you know, I am re-designing the README so we are more of a general scanner than an Nmap specific helper.
> 
> I have not pulled this because I am still writing the README :)

This redesign is almost complete. We can't merge this because it won't fit with the new re-design, sorry! :)

**Comment by SuperSandro2000** [comment]
> This redesign is almost complete. We can't merge this because it won't fit with the new re-design, sorry! :)

You could merge it to get the info in until that is done.

**Pull request closed without merging**
