### PR TITLE
Refactor RangeIterator to not require Option types

### PR DESCRIPTION
**Pull request by bernardoamc**
There's no need to deal with `unwrap` for this specific algorithm, instead we can rely on simple types to achieve the same result.

### CODE REVIEW

**Comment by brandonskerritt** [comment]
Cargo is having issues right now :) 

```
/download`, got 502

error: failed to download from `https://crates.io/api/v1/crates/gcd/2.0.1/download`

Caused by:

  failed to get 200 response from `https://crates.io/api/v1/crates/gcd/2.0.1/download`, got 502

The command "cargo build" exited with 101.
```

**Comment by brandonskerritt** [comment]
Do you still want me to merge this?

**Comment by bernardoamc** [comment]
Yeah, but let me adjust a few details 👍

**Comment by bernardoamc** [comment]
@brandonskerritt Ready for testing :)

**Pull request merged**
