### PR TITLE
Fixes #645: Add arm64 Docker image build

### LINKED ISSUE #645: Feature Request: Docker image for arm64
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 I would like to see a docker image for arm64. Currently I have built one myself, but being able to pull it would be nice. 

**Describe alternatives you've considered**
I've built one myself using your Dockerfile on my own computer for now. 

**Additional context**
Building for multiple architectures is pretty easy. Just run `docker build --platform linux/amd64,linux/arm64 -t rustscan/rustscan .`

### PR DESCRIPTION
**Pull request by mcamou**

### CODE REVIEW

**Comment by PsypherPunk** [comment]
@mcamou, this doesn't _quite_ work: the `platforms` addition is correct as per [the docs.](https://docs.docker.com/build/ci/github-actions/multi-platform/) but your changes fail with an error:

> _ERROR: Multi-platform build is not supported for the docker driver._

Based on those same docs. and some testing, it looks like we need the `docker/setup-buildx-action` too:

```yaml
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

With that in place both images appear to build correctly.

**Comment by mcamou** [comment]
@PsypherPunk thank you for that. I did it from memory and had forgotten about that. I've amended the commit and force-pushed to keep the commit history clean.

**Comment by PsypherPunk** [comment]
Looks good (and linking to [this](https://github.com/PsypherPunk/RustScan/actions/runs/11531057062/job/32101334533) as evidence)—thanks.

Happy Hacktoberfest!

**Review by PsypherPunk — APPROVED** [review]
Verified successful build [here](https://github.com/PsypherPunk/RustScan/actions/runs/11531057062/job/32101334533).

**Pull request merged**
