### PR TITLE
build and publish docker image in ci

### PR DESCRIPTION
**Pull request by LeoFVO**

### CODE REVIEW

**Comment by LeoFVO** [comment]
Close https://github.com/RustScan/RustScan/issues/471

**Comment by LeoFVO** [comment]
Hey @bee-san, I'm improving our DevOps flow by autodistribute docker image to stay updated with source code.

I will need you to set 2 github secrets if you're OK with that ;)

DOCKER_USERNAME your dockerhub username
DOCKER_PASSWORD your dockerhub token

**Comment by bee-san** [comment]
@LeoFVO 👋🏻  Thanks so much for all your help! I have some job interviews coming up so I am preparing for them, this is on my todo list

Annoyingly I yanked the crates.io token too accidentally 🙈  So I'll need to add that back in

I might spend a day or two investigating adding Lua support so we can have Nmap scripts too, think about how awesome that'd be! 

Equally I am distracted by building https://github.com/bee-san/Ares , lots of things going on 😅 

Just wanted to show my appreciation! If you set up a GitHub sponsors I'll sponsor you 👍🏻 <3

**Comment by bee-san** [comment]
Ok I've added docker read & write perms to the repo with the secrets :D 

I am rerunning it, equally I am trying to do the same thing over with the Discord bot at https://github.com/bee-san/discord-bot/blob/main/.github/workflows/docker-release.yml but failing 🙈

**Comment by bee-san** [comment]
Screenshot 2022-12-13 at 11 19 22

Not sure what's going on, I have the password & username set just like in the action 🤔  Maybe GitHub needs a moment to propagate it across all the replicas of whatever secret management system they're using 😂

**Comment by LeoFVO** [comment]
> Ok I've added docker read & write perms to the repo with the secrets :D
> 
> I am rerunning it, equally I am trying to do the same thing over with the Discord bot at https://github.com/bee-san/discord-bot/blob/main/.github/workflows/docker-release.yml but failing if you were bored enough to fix my mistakes joy see_no_evil (I should also say this needs to run on Arm7, which is why the Dockerfile looks so ugly for that repo)

I can take a look yeah ;)

**Comment by LeoFVO** [comment]
Okay I got it...
As said there https://github.com/docker/login-action/issues/29, we can't access env variable from fork. I think this is why... I don't know how to fix it :/

**Comment by bee-san** [comment]
> Okay I got it...
> As said there [docker/login-action#29](https://github.com/docker/login-action/issues/29), we can't access env variable from fork. I think this is why... I don't know how to fix it :/

Should I just merge and hope it works lol?

**Comment by LeoFVO** [comment]
> > Okay I got it...
> > As said there [docker/login-action#29](https://github.com/docker/login-action/issues/29), we can't access env variable from fork. I think this is why... I don't know how to fix it :/
> 
> Should I just merge and hope it works lol?

Ahh, maybe try to allow using secret from fork to run this job and disable after, no ? :D

**Comment by bee-san** [comment]
> > > Okay I got it...
> > > As said there [docker/login-action#29](https://github.com/docker/login-action/issues/29), we can't access env variable from fork. I think this is why... I don't know how to fix it :/
> > 
> > 
> > Should I just merge and hope it works lol?
> 
> Ahh, maybe try to allow using secret from fork to run this job and disable after, no ? :D

I do not think this is an option 🤔

**Comment by LeoFVO** [comment]
> > > > Okay I got it...
> > > > As said there [docker/login-action#29](https://github.com/docker/login-action/issues/29), we can't access env variable from fork. I think this is why... I don't know how to fix it :/
> > > 
> > > 
> > > Should I just merge and hope it works lol?
> > 
> > 
> > Ahh, maybe try to allow using secret from fork to run this job and disable after, no ? :D
> 
> I do not think this is an option thinking

Yeah I can't find it :/
I mean, Dockerfile can be reviewed and github action will be try in production :|

**Comment by bee-san** [comment]
> > > > > Okay I got it...
> > > > > As said there [docker/login-action#29](https://github.com/docker/login-action/issues/29), we can't access env variable from fork. I think this is why... I don't know how to fix it :/
> > > > 
> > > > 
> > > > Should I just merge and hope it works lol?
> > > 
> > > 
> > > Ahh, maybe try to allow using secret from fork to run this job and disable after, no ? :D
> > 
> > 
> > I do not think this is an option thinking
> 
> Yeah I can't find it :/ I mean, Dockerfile can be reviewed and github action will be try in production :|

We'll try in prod!

**Comment by bee-san** [comment]
Am I right in thinking I need to make a release for this? 👀

**Comment by CMNatic** [comment]
Yeah, looks like it's a problem with secrets. Also, the workflow is using `docker. password` for the password, I think we need to use `docker.token` instead?

**Pull request merged**
