### PR TITLE
Build CI to auto-distribute releases

### PR DESCRIPTION
**Pull request by LeoFVO**
Refactor developper CI.
Removed duplicate CI.
CI make release:

- build binary
- publish using cargo
- cross-compile

### CODE REVIEW

**Comment by bee-san** [comment]
Thanks for this <3 

Let me know if you need me to add anything to the secrets on GitHub for CI to run :)

**Comment by LeoFVO** [comment]
I'm going to be blocked due to this well know issue https://github.com/RustScan/RustScan/issues/171.
Also there is some code block to refactor to pass clippy tests, I'll try to fix some.

**Comment by bee-san** [comment]
Ahh Windows support shouldn't be that difficult, #449 upgraded the `rlimit` crate which adds support for Windows (which is why we didn't have it)

I do not have a Windows PC to test 🤔  but I imagine it's just fixing somethings until the CI works? 🤔

**Comment by LeoFVO** [comment]
I fixed all troubles about clippy, linting stage should pass now.
Also tried to fix test on window, need CI to be run to confirm.
Thanks ;)

**Comment by LeoFVO** [comment]
Hey @bee-san, I just fixed things and reorganized commits. Can you launch the github action to confirm please.
Also, we will need to set a github secret named : `CRATES_TOKEN` and the value have to be created from here https://crates.io/settings/tokens

Thanks for your help!

**Comment by LeoFVO** [comment]
It's seems that aarch64-linux doesn't have python pre-installed, I just removed aarch64 for now to check if release build work fine. Need CI to be triggered again.

**Comment by bee-san** [comment]
> It's seems that aarch64-linux doesn't have python pre-installed, I just removed aarch64 for now to check if release build work fine. Need CI to be triggered again.

Thanks! Apologies for GitHub CI making me approve it, once it's merged your future PRs will be auto-run 😅

**Comment by LeoFVO** [comment]
> 

It's OK :)
It's slow me a bit but np, If you want I can do a simple "fix typo" PR and you merge it to allow me auto-trigger the pipeline. As you want.

Btw, pipeline need to be trigger again :) windows is causing troubles xP

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
Thanks so much!!

**Pull request merged**
