### PR TITLE
Switch to tokio, and update dependencies

### PR DESCRIPTION
**Pull request by Vrtgs**
use tokio-par-streams  (this uses a FuturesUnordered<JoinHandle<T>> for FuturesParallelUnordered [see issue](https://github.com/tokio-rs/tokio/issues/5564)), and some test code improvement to conform to [this](https://rust-lang.github.io/rust-clippy/master/index.html#/field_reassign_with_default) lint, lastly updated to edition 2021

### CODE REVIEW

**Comment by Vrtgs** [comment]
this resolves #588

**Comment by 4FunAndProfit** [comment]
Hello @Vrtgs !

Do you know if the switch to tokio may help for adaptative outbound syn timing ? :) 

Check out the associated github issue 
This could be I think decisive for the switch to tokio I guess? :)
It would be amazing if it could help and kill two birds with one stone :DDD
You seem to know a lot about tokio so if possible, and if you have an idea, reply to the members on the other thread :D

**Comment by bee-san** [comment]
PR is blocked until we implement proper benchmarking

**Comment by bee-san** [comment]
No longer blocked, let's fix the merge conflicts and do some benchmarking 🥳

**Comment by Vrtgs** [comment]
Alright, just wondering how do you plan on benchmarking?

**Comment by bee-san** [comment]
Run `cargo bench` and see if much has changed :P

**Comment by bee-san** [comment]
Basically run cargo bench from master, and then run it again from this branch and we'll compare the 2 🤔

**Comment by Vrtgs** [comment]
new branch, since this is too outdated

**Pull request closed without merging**
