### PR TITLE
fix port range to include end

### LINKED ISSUE #515: --range <start-end>, only contain start, But not end port
In nmap run：**nmap 192.168.1.2 -p 1-65535** ,nmap scan port range is 1-65535.
But in RustScan run：**rustscan 192.168.1.2 --range 1-65535** (or directly execute **rustscan 192.168.1.2**) by wireshark verification, the scan range is 1-65534, does not contain 65535.

The same in nmap exec: **nmap 192.168.1.2 -p 1-5**, nmap scan range is 1-5.
But in the RustScan exec:  **rustscan 192.168.1.2 --range 1-5**, rustscan scan range is 1-4.

Please fix this bug.  Services open on 65535 may be missed when execute  full port scan.

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #515
Use close range for test and range generation.

### CODE REVIEW

**Comment by bee-san** [comment]
Hi! Mind pushing an empty commit? CI has failed to pick this up and I think it'll only pick it up on a new commit? 🤔

**Comment by hpmaxi** [comment]
> Hi! Mind pushing an empty commit? CI has failed to pick this up and I think it'll only pick it up on a new commit? 🤔

Done! `1 workflow awaiting approval`

**Comment by bee-san** [comment]
> > Hi! Mind pushing an empty commit? CI has failed to pick this up and I think it'll only pick it up on a new commit? 🤔
> 
> Done! `1 workflow awaiting approval`

Running!

**Comment by bee-san** [comment]
thank you!!

**Pull request merged**
