### PR TITLE
support --range 1-22,661-669,8888

### PR DESCRIPTION
**Pull request by Autumn-27**
Supports port range optional range and single port.
example:rustscan -a 127.0.0.1  --range 1-22,661-669,8888

### CODE REVIEW

**Comment by PsypherPunk** [comment]
Thanks for the PR. It'd be useful to understand what issues you were running into that prompted this change…?

Currently, there's a specific message around not having ranges and individual ports used; it'd be useful to understand if there's a reason for that or if it's just historical:

```sh
the argument '--ports <PORTS>' cannot be used with '--range <RANGE>'
```

That said, if `--range` starts managing both single ports and ranges, those parameters could be confusing and if folks are on board with this change it might be worth deprecating one or the other. I'll wait for other views on that.

Also, I'd suggest any comments are in English to be consistent with the existing codebase.

**Comment by Autumn-27** [comment]
https://github.com/RustScan/RustScan/issues/424
I have also seen someone mention it in the issue before, because currently I am doing integrated scanning, such as scanning the top 100 ports using 1-20, 808080-8088, etc. If it cannot be supported, I need to split all ports into individual ports - ports 1, 2, 3, 4... 20, 8080808081... 8088. There is no problem with a small number of ports, but if there are too many ports, it will exceed the command length limit at runtime. Hope it can be supported

**Comment by Autumn-27** [comment]
I think managing ports through just one is enough~

**Comment by Autumn-27** [comment]
I think this is more convenient

**Comment by bee-san** [comment]
> reason for that or if it's just historical

This took me back! This was a big, big argument we had. I think if I recall 4 years ago it simply was not possible for us to have both arguments at the same time. This is because the argument parsing library we used at the time was not mature enough to support these two things. It sounds insane now, but Rust was a different beast 4 years ago 😂  (I can't find our discussion on GitHub, might be in the old RustScan Discord)

> That said, if --range starts managing both single ports and ranges, those parameters could be confusing and if folks are on board with this change it might be worth deprecating one or the other. I'll wait for other views on that.

Yes I agree. There's also the speed issue, range now needs the ability to parse single ports which adds another loop into our code. For arguments it's fine, but I wonder if `parse_range` is used else where for example in the TOML definition of ports, it may slow down quite a bit.

I think a good solution is to keep both, and to allow both to be used at the same time. 

We use Clap now, so I would hope it's possible to use both arguments at the same time :) https://github.com/RustScan/RustScan/pull/591 

Also, the CI is failing. I'd suggest running these locally:
* Cargo test
* Cargo clippy
* Cargo fmt

And if all are okay, the CI will generally be ok :)

**Comment by Autumn-27** [comment]
I've considered supporting both parameters, but this still requires splitting the top 1000 common ports and then splicing them into the command line. Adding loops will indeed slow things down, but I think it's probably not a big deal? After all, a single port will only be traversed once. Or provide a completely new parameter?

**Comment by Autumn-27** [comment]
In addition, I am not very familiar with rust. I don't know if my changes will affect other codes. The program can run. There is indeed an error when running Cargo test. I will try to fix it.

**Comment by PsypherPunk** [comment]
@bee-san, just to clarify this (as I think it's worth continuing):

- `--ports` and `--range` should co-exist (rather than be mutually exclusive as currently.
- as per #424, should `--range` be extended to accept multiple, comma-separated ranges? Or should this be a separate `--ranges`?

**Pull request closed without merging**
