### PR TITLE
Progress bar for base scan progress

### LINKED ISSUE #88: Progress bars
**Describe the solution you'd like**
Progress bars that show progress would be neato

**Additional context**
https://crates.io/crates/indicatif

### PR DESCRIPTION
**Pull request by mattcorbin**
I added in a progress bar for the base `Scanner.run()`. I had to reorganize the `println!("Open {}", socket.to_string().purple());` to be after the scan finishes, as outputting that progress in addition to the bar caused the bar to keep getting pushed down and recreated. There may be a more sophisticated way to handle this as I'm not super familiar with either RustScan and the indicatif crate, so I wanted to post this up to get some preliminary feedback.

fixes #88

### CODE REVIEW

**Comment by bernardoamc** [comment]
Hey @mattcorbin, thanks for the contribution! This library has a heavy set of dependencies, do you know if the rust-world has any lightweight alternatives? :)

**Comment by mattcorbin** [comment]
@bernardoamc That was actually the crate linked in #88 so I just went with that one to start with. It looks like [pbr](https://crates.io/crates/pbr) is the main alternative, and looks to me to be a little bit lighter. I can try to swap it around to use pbr, as the other options I've found are either very beta or abandoned.

**Comment by mattcorbin** [comment]
@bernardoamc I swapped out `indicatif` for `pbr`, the code structure is identical and the actual progress bar itself seems quite a bit nicer IMO. Let me know what you think.

**Comment by bernardoamc** [comment]
This is awesome, thanks @mattcorbin. Could you rebase this with master? This is conflicting with my latest changes. 🙇

**Review by bernardoamc — APPROVED** [review]

**Comment by bernardoamc** [comment]
@bee-san do you want to run this PR locally? 😄

**Comment by bee-san** [comment]
Hey! Thanks so much for your work <3 Unfortunately we think a progress bar would be unmaintainable in the future as we need different types of scans / scripts etc. 

Thank you SO much for contributing though! You will get credit on the README for writing code (even if it wasn't merged) :D 

@all-contributors add @mattcorbin for code

**Pull request closed without merging**
