### PR TITLE
socket_iterator: use itertools.iproducts for ip x ports set

### PR DESCRIPTION
**Pull request by dmitris**
PR replaces the current manual iterator-like implementation in scanner/socket_iterator.rs
with the call to the itertools.iproduct macro [1] to generate the cartesian product
of the IPs and ports. I believe the reduction of the `SocketIterator` member variables and removing
the "manual" tracking of indexes and lengths makes the code easier to read and understand.

[1]
https://docs.rs/itertools/0.9.0/itertools/macro.iproduct.html

### CODE REVIEW

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@bernardoamc Fancy taking a look at this? :)

**Comment by bernardoamc** [comment]
Looks good, thank you for your contribution @dmitris! <3 Since we are introducing `itertools`as a dependency I will check if we can refactor other areas of the codebase with it.

**Review by bernardoamc — APPROVED** [review]

**Comment by dmitris** [comment]
@bernardoamc shall I rebase on master / force-push, or not worth to kill the two approvals that would need to be repeated?

**Comment by bee-san** [comment]
> @bernardoamc shall I rebase on master / force-push, or not worth to kill the two approvals that would need to be repeated?

you only need one approval and I can do it pretty quickly :)

**Comment by bee-san** [comment]
@all-contributors please add @dmitris for code

**Pull request merged**
