### PR TITLE
Add tests for rustscan scripting engine (#286)

### PR DESCRIPTION
**Pull request by okrplay**
I've used @bergabman's test files. One test checks if the script is correctly parsed (using the example .txt), the other three tests run the scripts and check the output. They're not ignored, so bash, python3 and perl have to be available for the tests, I could change that though. I only check if the .txt is parsed correctly as the output is from nmap and changes every time, as it includes e.g. execution time. No test actually executes a scan, I just pass some test values to `Script::build()`.
`ports` in the scripting config example was an array of integers, while the parses expects a `Vec` of `Strings`, I changed the config according to that.

### CODE REVIEW

**Comment by bee-san** [comment]
Hey! Thanks so much for contributing :sparkling_heart: 

I just noticed that `timelimits.rs` tests are ignored, can you un-ignore them please? 

Our Code Coverage is quite low because of it :( 

```
|| Tested/Total Lines:
|| src/benchmark/mod.rs: 24/26 +0%
|| src/input.rs: 40/43 +2.7793533749290944%
|| src/main.rs: 134/143 +1.64280164280165%
|| src/port_strategy/mod.rs: 51/52 +0%
|| src/port_strategy/range_iterator.rs: 44/45 +0%
|| src/scanner/mod.rs: 65/70 +13.588850174216027%
|| src/scanner/socket_iterator.rs: 21/21 +0%
|| src/scripts/mod.rs: 84/145
|| tests/timelimits.rs: 0/15
|| 
82.68% coverage, 463/560 lines covered, -8.415576154125787% change in coverage```

**Comment by okrplay** [comment]
I added a test to cover the rest of the functions in the scripting module. I haven't worked with coverage tools before, but I saw that functions that did something in the home directory were not included in the coverage, so I did that with another function which required files in the home directory too.
The tests in `timelimits.rs` had a comment about them saying they should be ignored, so I disabled coverage for the function in that file.

**Comment by okrplay** [comment]
```
Oct 18 00:14:03.111  INFO cargo_tarpaulin::report: Coverage Results:
|| Tested/Total Lines:
|| src/benchmark/mod.rs: 24/26 +0%
|| src/input.rs: 43/45 +0%
|| src/main.rs: 141/153 +0%
|| src/port_strategy/mod.rs: 51/52 +0%
|| src/port_strategy/range_iterator.rs: 44/45 +0%
|| src/scanner/mod.rs: 65/71 +0%
|| src/scanner/socket_iterator.rs: 21/21 +0%
|| src/scripts/mod.rs: 120/125 +0%
||
94.61% coverage, 509/538 lines covered, +0% change in coverage
```
I figured out how to generate Tarpaulin html reports and the uncovered lines are all in between covered lines, I don't really know how I could cover those lines. Apart from that I've refactored some test code.

**Comment by bee-san** [comment]
> ```
> Oct 18 00:14:03.111  INFO cargo_tarpaulin::report: Coverage Results:
> || Tested/Total Lines:
> || src/benchmark/mod.rs: 24/26 +0%
> || src/input.rs: 43/45 +0%
> || src/main.rs: 141/153 +0%
> || src/port_strategy/mod.rs: 51/52 +0%
> || src/port_strategy/range_iterator.rs: 44/45 +0%
> || src/scanner/mod.rs: 65/71 +0%
> || src/scanner/socket_iterator.rs: 21/21 +0%
> || src/scripts/mod.rs: 120/125 +0%
> ||
> 94.61% coverage, 509/538 lines covered, +0% change in coverage
> ```
> 
> I figured out how to generate Tarpaulin HTML reports and the uncovered lines are all in between covered lines, I don't really know how I could cover those lines. Apart from that I've refactored some test code.

Hahaha HTML reports? That's more advanced than what I do :sweat_smile: It's probably because, I assume, a test only checks the first match in a if / match statement? Anyway -- 94% is very good :)

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@all-contributors please add @okrplay for code and testing

**Comment by bergabman** [comment]
Awesome PR, thanks for your contribution! 💯

**Comment by okrplay** [comment]
> > ```
> > Oct 18 00:14:03.111  INFO cargo_tarpaulin::report: Coverage Results:
> > || Tested/Total Lines:
> > || src/benchmark/mod.rs: 24/26 +0%
> > || src/input.rs: 43/45 +0%
> > || src/main.rs: 141/153 +0%
> > || src/port_strategy/mod.rs: 51/52 +0%
> > || src/port_strategy/range_iterator.rs: 44/45 +0%
> > || src/scanner/mod.rs: 65/71 +0%
> > || src/scanner/socket_iterator.rs: 21/21 +0%
> > || src/scripts/mod.rs: 120/125 +0%
> > ||
> > 94.61% coverage, 509/538 lines covered, +0% change in coverage
> > ```
> > 
> > 
> > I figured out how to generate Tarpaulin HTML reports and the uncovered lines are all in between covered lines, I don't really know how I could cover those lines. Apart from that I've refactored some test code.
> 
> Hahaha HTML reports? That's more advanced than what I do 😅 It's probably because, I assume, a test only checks the first match in a if / match statement? Anyway -- 94% is very good :)

I ended up writing tests that cover every if/match statement. The HTML report is just a copy of the code marked green and red, it's pretty useful, only found out that you could generate it when I was already done with all the tests though 😅. I've attached two screenshots showing the five uncovered lines.
image
image

**Pull request merged**
