### PR TITLE
Optimize Dockerfile

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This shouldn't change the function of the Dockerimage at all but makes the Dockerfile more maintainable and the cache is no longer being busted when doing simple git operations.

PS: I am also working on a nixos package. :shushing_face:

### CODE REVIEW

**Review by brandonskerritt — APPROVED** [review]

**Comment by brandonskerritt** [comment]
Is your NixOS package fall under one of these:
```
nixpkgs stable
nixpkgs unstable
```? 

If so, it will be automatically added to the README under Repoology :D 

https://repology.org/project/rustscan/versions

@all-contributors please add @SuperSandro2000 for packaging, bugs, and code

Thanks a lot for this! :sparkles:

**Comment by brandonskerritt** [comment]
@all-contributors please add @SuperSandro2000 for packaging, bugs, and code

**Comment by SuperSandro2000** [comment]
@brandonskerritt When it is merged, yes. I am currently testing it and waiting for my first PR to get me as a maintainer in.

**Comment by SuperSandro2000** [comment]
If you want to follow the PR it is available here https://github.com/NixOS/nixpkgs/pull/96576.

**Pull request merged**
